### ISSUE TITLE
Failed to setup on M1 Mac: Cannot install grpcio 1.51.1

### ISSUE THREAD

**Issue by DeepController** [octoml/octoml-profile#9]
**Describe the bug**
Following the instruction to setup on my M1 Mac mini. Cannot install `grpcio` when running
```
pip install grpcio==1.51.1
```
The issue might be resolved in `grpcio==1.51.3`: https://github.com/grpc/grpc/issues/25082.

**To Reproduce**
```
conda create -n octoml python=3.8
conda activate octoml
pip install --pre "torch>=2.0.0dev" "torchvision>=0.15.0.dev" "torchaudio>=2.0.0dev" --extra-index-url https://download.pytorch.org/whl/nightly/cpu
pip install octoml-profile
conda install onnx=1.12.0
pip install grpcio==1.51.1 grpcio-tools==1.48.2
```
The error message is too long, please see this link for entire output: https://asciinema.org/a/563434

If I install the `onnx` and `grpcio` before installing the `octoml-profile`, the issue seems to disappear, but there's another error message:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.12.0 requires protobuf<=3.20.1,>=3.12.2, but you have protobuf 3.20.3 which is incompatible.
```

**Expected behavior**
Successfully install `grpcio==1.51.1`

**Error Output**
The error message is too long, please see this link for entire output: https://asciinema.org/a/563434

**System Information:**
 - OS: macos Ventura 13.2
 - CPU: Apple M1
 - GCC:

 ```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by haijieg** [comment]
Hi @DeepController, thanks for reporting the issue.

I can reproduce the issue with `miniconda3` but not with `conda-forge`.
Using `Miniconda3`, I found the following steps works:

```
# Instructions on installing conda on MacOS: https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html
conda install onnx=1.12.0 grpcio=1.42.0 grpcio-tools=1.16.1
```

Please let me know if your problem is resolve. We will update the installation instruction accordingly.

**Comment by dnlby96** [comment]
Hi @DeepController, we have made the installation instructions simpler for M1 machines. Please let us know if the new instructions work for you.

**Comment by DeepController** [comment]
Hi @dnlby96 @haijieg 

Thank you both! I am able to install everything and successfully ran octoml-profile with the following commands
```
conda create -n octoml python=3.8
conda activate octoml
conda install onnx=1.12.0 grpcio=1.42.0 grpcio-tools=1.16.1
pip install "torch>=2.0.0" "torchvision>=0.15.0" "torchaudio>=2.0.0" --index-url https://download.pytorch.org/whl/test/cpu
pip install octoml-profile
```

But I've noticed that the instruction specific to M1 Mac has been removed from the README. Is this intended? Does it mean I don't need to install `onnx` and `grpcio` in order to setup octoml?

**Comment by DeepController** [comment]
BTW in the example folder README, there's an instruction to install `transformers==4.25.0`, but 4.25.0 is an yanked version. Better to update it to install 4.25.1?

**Comment by dnlby96** [comment]
> But I've noticed that the instruction specific to M1 Mac has been removed from the README. Is this intended? Does it mean I don't need to install `onnx` and `grpcio` in order to setup octoml?
@DeepController That's right. The compatible `onnx` and `grpcio` will now be automatically installed when you pip install octoml-profile.


> BTW in the example folder README, there's an instruction to install `transformers==4.25.0`, but 4.25.0 is an yanked version. Better to update it to install 4.25.1?
Thank you so much for the tip! We will update it asap.
